import { ProductEnum, ProductType } from "../type";
import { onePieceImageList, bleachImageList, demonSlayerImageList, dragonBallImageList, narutoImageList } from "../imageList";

const productsList: ProductType[] = [
    // Naruto Products
    { id: 1, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 1', price: 19.99, description: 'Le premier volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 5, votes: 120 },
    { id: 2, type: ProductEnum.NARUTO, title: 'Peluche Naruto', price: 25.99, description: 'Une peluche de Naruto.', imagePath: narutoImageList.peluche, rating: 4, votes: 85 },
    { id: 3, type: ProductEnum.NARUTO, title: 'Jeu Vidéo Naruto', price: 59.99, description: 'Un jeu vidéo basé sur Naruto Shippuden.', imagePath: narutoImageList.game, rating: 3, votes: 200 },
    { id: 4, type: ProductEnum.NARUTO, title: 'Figurine Naruto', price: 34.99, description: 'Une figurine de Naruto.', imagePath: narutoImageList.figurine, rating: 5, votes: 150 },
    { id: 5, type: ProductEnum.NARUTO, title: 'Sweat Naruto', price: 49.99, description: 'Un sweat à capuche avec le design de Naruto.', imagePath: narutoImageList.sweat, rating: 4, votes: 300 },
    { id: 6, type: ProductEnum.NARUTO, title: 'Poster Naruto', price: 9.99, description: 'Un poster de Naruto Shippuden.', imagePath: narutoImageList.poster, rating: 2, votes: 50 },
    { id: 7, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 2', price: 19.99, description: 'Le deuxième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 4, votes: 100 },
    { id: 8, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 3', price: 19.99, description: 'Le troisième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 3, votes: 90 },
    { id: 9, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 4', price: 19.99, description: 'Le quatrième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 5, votes: 130 },
    { id: 10, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 5', price: 19.99, description: 'Le cinquième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 4, votes: 140 },
    { id: 11, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 6', price: 19.99, description: 'Le sixième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 3, votes: 110 },
    { id: 12, type: ProductEnum.NARUTO, title: 'Porte-clés Naruto', price: 7.99, description: 'Un porte-clés avec le design de Naruto.', imagePath: narutoImageList.key, rating: 2, votes: 40 },
    { id: 13, type: ProductEnum.NARUTO, title: 'Mug Naruto', price: 14.99, description: 'Un mug avec le design de Naruto.', imagePath: narutoImageList.mug, rating: 5, votes: 70 },
    { id: 14, type: ProductEnum.NARUTO, title: 'Sac à dos Naruto', price: 39.99, description: 'Un sac à dos avec le design de Naruto.', imagePath: narutoImageList.bag, rating: 4, votes: 95 },
    { id: 15, type: ProductEnum.NARUTO, title: 'Coque de téléphone Naruto', price: 12.99, description: 'Une coque de téléphone avec le design de Naruto.', imagePath: narutoImageList.phone, rating: 3, votes: 60 },
    { id: 16, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 7', price: 19.99, description: 'Le septième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 5, votes: 125 },
    { id: 17, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 8', price: 19.99, description: 'Le huitième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 4, votes: 135 },
    { id: 18, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 9', price: 19.99, description: 'Le neuvième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 3, votes: 105 },
    { id: 19, type: ProductEnum.NARUTO, title: 'Naruto Shippuden Vol. 10', price: 19.99, description: 'Le dixième volume de Naruto Shippuden.', imagePath: narutoImageList.tome, rating: 5, votes: 145 },
    { id: 20, type: ProductEnum.NARUTO, title: 'Casquette Naruto', price: 21.99, description: 'Une casquette avec le design de Naruto.', imagePath: narutoImageList.tome, rating: 4, votes: 160 },

    // One Piece Products
    { id: 21, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 1', price: 19.99, description: 'Le premier volume de One Piece.', imagePath: onePieceImageList.tome, rating: 5, votes: 130 },
    { id: 22, type: ProductEnum.ONE_PIECE, title: 'Peluche One Piece', price: 25.99, description: 'Une peluche de personnage de One Piece.', imagePath: onePieceImageList.peluche, rating: 4, votes: 90 },
    { id: 23, type: ProductEnum.ONE_PIECE, title: 'Jeu Vidéo One Piece', price: 59.99, description: 'Un jeu vidéo basé sur One Piece.', imagePath: onePieceImageList.game, rating: 3, votes: 200 },
    { id: 24, type: ProductEnum.ONE_PIECE, title: 'Figurine One Piece', price: 34.99, description: 'Une figurine de personnage de One Piece.', imagePath: onePieceImageList.figurine, rating: 5, votes: 160 },
    { id: 25, type: ProductEnum.ONE_PIECE, title: 'Sweat One Piece', price: 49.99, description: 'Un sweat à capuche avec le design de One Piece.', imagePath: onePieceImageList.sweat, rating: 4, votes: 290 },
    { id: 26, type: ProductEnum.ONE_PIECE, title: 'Poster One Piece', price: 9.99, description: 'Un poster de One Piece.', imagePath: onePieceImageList.tome, rating: 2, votes: 60 },
    { id: 27, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 2', price: 19.99, description: 'Le deuxième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 4, votes: 100 },
    { id: 28, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 3', price: 19.99, description: 'Le troisième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 3, votes: 80 },
    { id: 29, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 4', price: 19.99, description: 'Le quatrième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 5, votes: 120 },
    { id: 30, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 5', price: 19.99, description: 'Le cinquième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 4, votes: 110 },
    { id: 31, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 6', price: 19.99, description: 'Le sixième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 3, votes: 140 },
    { id: 32, type: ProductEnum.ONE_PIECE, title: 'Porte-clés One Piece', price: 7.99, description: 'Un porte-clés avec le design de One Piece.', imagePath: onePieceImageList.key, rating: 2, votes: 40 },
    { id: 33, type: ProductEnum.ONE_PIECE, title: 'Mug One Piece', price: 14.99, description: 'Un mug avec le design de One Piece.', imagePath: onePieceImageList.mug, rating: 5, votes: 70 },
    { id: 34, type: ProductEnum.ONE_PIECE, title: 'Sac à dos One Piece', price: 39.99, description: 'Un sac à dos avec le design de One Piece.', imagePath: onePieceImageList.bag, rating: 4, votes: 95 },
    { id: 35, type: ProductEnum.ONE_PIECE, title: 'Coque de téléphone One Piece', price: 12.99, description: 'Une coque de téléphone avec le design de One Piece.', imagePath: onePieceImageList.phone, rating: 3, votes: 60 },
    { id: 36, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 7', price: 19.99, description: 'Le septième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 5, votes: 125 },
    { id: 37, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 8', price: 19.99, description: 'Le huitième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 4, votes: 135 },
    { id: 38, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 9', price: 19.99, description: 'Le neuvième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 3, votes: 105 },
    { id: 39, type: ProductEnum.ONE_PIECE, title: 'One Piece Vol. 10', price: 19.99, description: 'Le dixième volume de One Piece.', imagePath: onePieceImageList.tome, rating: 5, votes: 145 },
    { id: 40, type: ProductEnum.ONE_PIECE, title: 'Casquette One Piece', price: 21.99, description: 'Une casquette avec le design de One Piece.', imagePath: onePieceImageList.casquette, rating: 4, votes: 160 },

    // Dragon Ball Products
    { id: 41, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 1', price: 19.99, description: 'Le premier volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 5, votes: 130 },
    { id: 42, type: ProductEnum.DRAGON_BALL, title: 'Peluche Dragon Ball', price: 25.99, description: 'Une peluche de personnage de Dragon Ball.', imagePath: dragonBallImageList.peluche, rating: 4, votes: 90 },
    { id: 43, type: ProductEnum.DRAGON_BALL, title: 'Jeu Vidéo Dragon Ball', price: 59.99, description: 'Un jeu vidéo basé sur Dragon Ball.', imagePath: dragonBallImageList.game, rating: 3, votes: 200 },
    { id: 44, type: ProductEnum.DRAGON_BALL, title: 'Figurine Dragon Ball', price: 34.99, description: 'Une figurine de personnage de Dragon Ball.', imagePath: dragonBallImageList.figurine, rating: 5, votes: 160 },
    { id: 45, type: ProductEnum.DRAGON_BALL, title: 'Sweat Dragon Ball', price: 49.99, description: 'Un sweat à capuche avec le design de Dragon Ball.', imagePath: dragonBallImageList.sweat, rating: 4, votes: 290 },
    { id: 46, type: ProductEnum.DRAGON_BALL, title: 'Poster Dragon Ball', price: 9.99, description: 'Un poster de Dragon Ball.', imagePath: dragonBallImageList.poster, rating: 2, votes: 60 },
    { id: 47, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 2', price: 19.99, description: 'Le deuxième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 4, votes: 100 },
    { id: 48, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 3', price: 19.99, description: 'Le troisième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 3, votes: 80 },
    { id: 49, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 4', price: 19.99, description: 'Le quatrième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 5, votes: 120 },
    { id: 50, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 5', price: 19.99, description: 'Le cinquième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 4, votes: 110 },
    { id: 51, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 6', price: 19.99, description: 'Le sixième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 3, votes: 140 },
    { id: 52, type: ProductEnum.DRAGON_BALL, title: 'Porte-clés Dragon Ball', price: 7.99, description: 'Un porte-clés avec le design de Dragon Ball.', imagePath: dragonBallImageList.key, rating: 2, votes: 40 },
    { id: 53, type: ProductEnum.DRAGON_BALL, title: 'Mug Dragon Ball', price: 14.99, description: 'Un mug avec le design de Dragon Ball.', imagePath: dragonBallImageList.mug, rating: 5, votes: 70 },
    { id: 54, type: ProductEnum.DRAGON_BALL, title: 'Sac à dos Dragon Ball', price: 39.99, description: 'Un sac à dos avec le design de Dragon Ball.', imagePath: dragonBallImageList.bag, rating: 4, votes: 95 },
    { id: 55, type: ProductEnum.DRAGON_BALL, title: 'Coque de téléphone Dragon Ball', price: 12.99, description: 'Une coque de téléphone avec le design de Dragon Ball.', imagePath: dragonBallImageList.phone, rating: 3, votes: 60 },
    { id: 56, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 7', price: 19.99, description: 'Le septième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 5, votes: 125 },
    { id: 57, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 8', price: 19.99, description: 'Le huitième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 4, votes: 135 },
    { id: 58, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 9', price: 19.99, description: 'Le neuvième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 3, votes: 105 },
    { id: 59, type: ProductEnum.DRAGON_BALL, title: 'Dragon Ball Vol. 10', price: 19.99, description: 'Le dixième volume de Dragon Ball.', imagePath: dragonBallImageList.tome, rating: 5, votes: 145 },
    { id: 60, type: ProductEnum.DRAGON_BALL, title: 'Casquette Dragon Ball', price: 21.99, description: 'Une casquette avec le design de Dragon Ball.', imagePath: dragonBallImageList.casquette, rating: 4, votes: 160 },

    // Bleach Products
    { id: 61, type: ProductEnum.BLEACH, title: 'Bleach Vol. 1', price: 19.99, description: 'Le premier volume de Bleach.', imagePath: bleachImageList.tome, rating: 5, votes: 130 },
    { id: 62, type: ProductEnum.BLEACH, title: 'Peluche Bleach', price: 25.99, description: 'Une peluche de personnage de Bleach.', imagePath: bleachImageList.peluche, rating: 4, votes: 90 },
    { id: 63, type: ProductEnum.BLEACH, title: 'Jeu Vidéo Bleach', price: 59.99, description: 'Un jeu vidéo basé sur Bleach.', imagePath: bleachImageList.game, rating: 3, votes: 200 },
    { id: 64, type: ProductEnum.BLEACH, title: 'Figurine Bleach', price: 34.99, description: 'Une figurine de personnage de Bleach.', imagePath: bleachImageList.figurine, rating: 5, votes: 160 },
    { id: 65, type: ProductEnum.BLEACH, title: 'Sweat Bleach', price: 49.99, description: 'Un sweat à capuche avec le design de Bleach.', imagePath: bleachImageList.sweat, rating: 4, votes: 290 },
    { id: 66, type: ProductEnum.BLEACH, title: 'Poster Bleach', price: 9.99, description: 'Un poster de Bleach.', imagePath: bleachImageList.poster, rating: 2, votes: 60 },
    { id: 67, type: ProductEnum.BLEACH, title: 'Bleach Vol. 2', price: 19.99, description: 'Le deuxième volume de Bleach.', imagePath: bleachImageList.tome, rating: 4, votes: 100 },
    { id: 68, type: ProductEnum.BLEACH, title: 'Bleach Vol. 3', price: 19.99, description: 'Le troisième volume de Bleach.', imagePath: bleachImageList.tome, rating: 3, votes: 80 },
    { id: 69, type: ProductEnum.BLEACH, title: 'Bleach Vol. 4', price: 19.99, description: 'Le quatrième volume de Bleach.', imagePath: bleachImageList.tome, rating: 5, votes: 120 },
    { id: 70, type: ProductEnum.BLEACH, title: 'Bleach Vol. 5', price: 19.99, description: 'Le cinquième volume de Bleach.', imagePath: bleachImageList.tome, rating: 4, votes: 110 },
    { id: 71, type: ProductEnum.BLEACH, title: 'Bleach Vol. 6', price: 19.99, description: 'Le sixième volume de Bleach.', imagePath: bleachImageList.tome, rating: 3, votes: 140 },
    { id: 72, type: ProductEnum.BLEACH, title: 'Porte-clés Bleach', price: 7.99, description: 'Un porte-clés avec le design de Bleach.', imagePath: bleachImageList.key, rating: 2, votes: 40 },
    { id: 73, type: ProductEnum.BLEACH, title: 'Mug Bleach', price: 14.99, description: 'Un mug avec le design de Bleach.', imagePath: bleachImageList.mug, rating: 5, votes: 70 },
    { id: 74, type: ProductEnum.BLEACH, title: 'Sac à dos Bleach', price: 39.99, description: 'Un sac à dos avec le design de Bleach.', imagePath: bleachImageList.bag, rating: 4, votes: 95 },
    { id: 75, type: ProductEnum.BLEACH, title: 'Coque de téléphone Bleach', price: 12.99, description: 'Une coque de téléphone avec le design de Bleach.', imagePath: bleachImageList.phone, rating: 3, votes: 60 },
    { id: 76, type: ProductEnum.BLEACH, title: 'Bleach Vol. 7', price: 19.99, description: 'Le septième volume de Bleach.', imagePath: bleachImageList.tome, rating: 5, votes: 125 },
    { id: 77, type: ProductEnum.BLEACH, title: 'Bleach Vol. 8', price: 19.99, description: 'Le huitième volume de Bleach.', imagePath: bleachImageList.tome, rating: 4, votes: 135 },
    { id: 78, type: ProductEnum.BLEACH, title: 'Bleach Vol. 9', price: 19.99, description: 'Le neuvième volume de Bleach.', imagePath: bleachImageList.tome, rating: 3, votes: 105 },
    { id: 79, type: ProductEnum.BLEACH, title: 'Bleach Vol. 10', price: 19.99, description: 'Le dixième volume de Bleach.', imagePath: bleachImageList.tome, rating: 5, votes: 145 },
    { id: 80, type: ProductEnum.BLEACH, title: 'Casquette Bleach', price: 21.99, description: 'Une casquette avec le design de Bleach.', imagePath: bleachImageList.casquette, rating: 4, votes: 160 },

    // Demon Slayer Products
    { id: 121, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 1', price: 19.99, description: 'Le premier volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 5, votes: 130 },
    { id: 122, type: ProductEnum.DEMON_SLAYER, title: 'Peluche Demon Slayer', price: 25.99, description: 'Une peluche de personnage de Demon Slayer.', imagePath: demonSlayerImageList.peluche, rating: 4, votes: 90 },
    { id: 123, type: ProductEnum.DEMON_SLAYER, title: 'Jeu Vidéo Demon Slayer', price: 59.99, description: 'Un jeu vidéo basé sur Demon Slayer.', imagePath: demonSlayerImageList.game, rating: 3, votes: 200 },
    { id: 124, type: ProductEnum.DEMON_SLAYER, title: 'Figurine Demon Slayer', price: 34.99, description: 'Une figurine de personnage de Demon Slayer.', imagePath: demonSlayerImageList.figurine, rating: 5, votes: 160 },
    { id: 125, type: ProductEnum.DEMON_SLAYER, title: 'Sweat Demon Slayer', price: 49.99, description: 'Un sweat à capuche avec le design de Demon Slayer.', imagePath: demonSlayerImageList.sweat, rating: 4, votes: 290 },
    { id: 126, type: ProductEnum.DEMON_SLAYER, title: 'Poster Demon Slayer', price: 9.99, description: 'Un poster de Demon Slayer.', imagePath: demonSlayerImageList.poster, rating: 2, votes: 60 },
    { id: 127, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 2', price: 19.99, description: 'Le deuxième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 4, votes: 100 },
    { id: 128, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 3', price: 19.99, description: 'Le troisième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 3, votes: 80 },
    { id: 129, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 4', price: 19.99, description: 'Le quatrième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 5, votes: 120 },
    { id: 130, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 5', price: 19.99, description: 'Le cinquième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 4, votes: 110 },
    { id: 131, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 6', price: 19.99, description: 'Le sixième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 3, votes: 140 },
    { id: 132, type: ProductEnum.DEMON_SLAYER, title: 'Porte-clés Demon Slayer', price: 7.99, description: 'Un porte-clés avec le design de Demon Slayer.', imagePath: demonSlayerImageList.key, rating: 2, votes: 40 },
    { id: 133, type: ProductEnum.DEMON_SLAYER, title: 'Mug Demon Slayer', price: 14.99, description: 'Un mug avec le design de Demon Slayer.', imagePath: demonSlayerImageList.mug, rating: 5, votes: 70 },
    { id: 134, type: ProductEnum.DEMON_SLAYER, title: 'Sac à dos Demon Slayer', price: 39.99, description: 'Un sac à dos avec le design de Demon Slayer.', imagePath: demonSlayerImageList.bag, rating: 4, votes: 95 },
    { id: 135, type: ProductEnum.DEMON_SLAYER, title: 'Coque de téléphone Demon Slayer', price: 12.99, description: 'Une coque de téléphone avec le design de Demon Slayer.', imagePath: demonSlayerImageList.phone, rating: 3, votes: 60 },
    { id: 136, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 7', price: 19.99, description: 'Le septième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 5, votes: 125 },
    { id: 137, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 8', price: 19.99, description: 'Le huitième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 4, votes: 135 },
    { id: 138, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 9', price: 19.99, description: 'Le neuvième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 3, votes: 105 },
    { id: 139, type: ProductEnum.DEMON_SLAYER, title: 'Demon Slayer Vol. 10', price: 19.99, description: 'Le dixième volume de Demon Slayer.', imagePath: demonSlayerImageList.tome, rating: 5, votes: 145 },
    { id: 140, type: ProductEnum.DEMON_SLAYER, title: 'Casquette Demon Slayer', price: 21.99, description: 'Une casquette avec le design de Demon Slayer.', imagePath: demonSlayerImageList.casquette, rating: 4, votes: 160 },
];

export default productsList;